AWSTemplateFormatVersion: '2010-09-09'
Description: Create 3 EC2 instances with fixed IP addresses, configure passwordless SSH, and assign 50GB disk size

Parameters:
  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.large
    AllowedValues: [t2.micro, t2.small, t2.medium, t2.large]
    ConstraintDescription: Must be a valid EC2 instance type.
  
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: Must be the name of an existing EC2 KeyPair.

  EC2ImageId:
    Description: EC2 will based on this IMAGE to be created
    Type: String
    ConstraintDescription: Must be a valid AMI ID.

Resources:
  ZjtTestInstancesSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow all traffic
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: "-1" # Allow all protocols
          CidrIp: "0.0.0.0/0" # Allow traffic from any IP address

  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 192.168.0.0/24
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: HadoopInstancesVPC

  Subnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 192.168.0.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: HadoopInstancesSubnet

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: HadoopInstancesInternetGateway

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: ZjtTestInstancesRouteTable

  Route:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  SubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref Subnet
      RouteTableId: !Ref RouteTable

  Node:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      SecurityGroupIds:
        - !Ref ZjtTestInstancesSecurityGroup
      KeyName: !Ref KeyName
      ImageId: !Ref EC2ImageId
      SubnetId: !Ref Subnet
      PrivateIpAddress: 192.168.0.101
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: 50
      UserData: !Base64 |
        #!/bin/bash
        yum update -y
        yum install -y openssh-clients
        sudo yum -y install wget gcc gcc-c++ autoconf automake make
      Tags:
        - Key: Name
          Value: Node

Outputs:
  VPCId:
    Description: VPC ID
    Value: !Ref VPC

  SubnetId:
    Description: Subnet ID
    Value: !Ref Subnet

  NodeId:
    Description: Instance ID of the first EC2 instance
    Value: !Ref Node
